import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/vanilla.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Add Post Functionality",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
